# DATABASE

spring.datasource.url=jdbc:postgresql://updatecheck_user:rUduZX9tEntJxW0kzjBxHnxPldja8e5l@dpg-d6n49ka4d50c73d8rll0-a.oregon-postgres.render.com/updatecheck
spring.datasource.username=updatecheckdb_user
spring.datasource.password=rUduZX9tEntJxW0kzjBxHnxPldja8e5l

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# H2 (disable in production)
spring.h2.console.enabled=false


# MAIL CONFIG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=updatecheck601@gmail.com
spring.mail.password=syse cjbx dmlg zirh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true