# DATABASE

spring.datasource.url=jdbc:postgresql://dpg-xxxxx-a.oregon-postgres.render.com:5432/updatecheckdb
spring.datasource.username=updatecheckdb_user
spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# H2 (disable in production)
spring.h2.console.enabled=false


# MAIL CONFIG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=updatecheck601@gmail.com
spring.mail.password=syse cjbx dmlg zirh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true