SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d6ml8dua2pns73d8ibpg-a:5432/DATABASE
SPRING_DATASOURCE_USERNAME=updatecheck_db_user
SPRING_DATASOURCE_PASSWORD=12zSxshRjGmRxwdTKCaVcN4m69TmKJX5
SPRING_JPA_HIBERNATE_DDL_AUTO=update
SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# MAIL CONFIG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=updatecheck601@gmail.com
spring.mail.password=syse cjbx dmlg zirh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true